### ISSUE TITLE
Verify existence '.eslintrc.* file also :(

### ISSUE THREAD

**Issue by guilhermeesteves-luizalabs** [GuilhermeEsteves/git-hook-eslint#3]
Before create '.eslintrc' file, verify existence '.eslintrc.*' because don't need multiple files. #

**Comment by lganet** [comment]
We'll do this **soon**.

**Comment by GuilhermeEsteves** [comment]
Issue fix. :1st_place_medal:

**Comment by GuilhermeEsteves** [comment]
Issue fix. 1st_place_medal
